name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        cd "Experiment 16/Testing/Backend"
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd "Experiment 16/Testing/Backend"
        pytest

    - name: Build Docker Image
      run: |
        cd "Experiment 16/Testing/Backend"
        docker build -t flask-testing-app .